site_name: Maven 101
site_author: Jonas Jurczok (jonas.jurczok@zalando.de)

repo_url: https://stash.zalando.net/projects/MENT/repos/maven101/browse
repo_name: Stash

theme: united

use_directory_urls: false
strict: true

docs_dir: tasks
pages:
- Introduction: index.md
- Theory: theory.md
- Tasks:
  - Basic Project Setup: 01_basic_setup/basic_setup.md
  - Adding Dependencies: 02_dependencies/dependencies.md